services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    command: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  django_permition:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    environment:
      DJANGO_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-permition}
      DJANGO_DATABASE_USER: ${POSTGRES_USER:-permition}
      DJANGO_DATABASE_NAME: ${DJANGO_DATABASE_NAME:-permition}
      POSTGRES_HOST: ${POSTGRES_HOST:-django_permition-db-1}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - .:/usr/src:cached
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  pgdata:
